services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\EngineWP\Hooks\:
        resource: '../src/Hooks/*'
        public: true
